### Do your work for this exercise in either a python file named simulation.py or a jupyter notebook named simulation.ipynb.

### 1. How likely is it that you roll doubles when rolling two dice?

In [1]:
import numpy as np
import pandas as pd
import random
np.random.seed(29)

In [2]:
die1 = np.random.choice([1, 2, 3, 4, 5 ,6], 10_000)
die2 = np.random.choice([1, 2, 3, 4, 5, 6], 10_000)

samesies = die1 == die2
samesies.mean()

0.1613

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [3]:
nrows = 100_000 
ncols = 8       


In [4]:
rolls = np.random.choice([True, False], nrows * ncols).reshape(nrows, ncols)


In [5]:
df = pd.DataFrame(rolls)
df.head()

0      1      2      3      4      5      6      7
0   True   True   True   True  False   True  False  False
1   True   True  False  False  False  False  False   True
2  False   True  False   True  False  False  False  False
3   True  False   True   True   True   True  False  False
4  False   True   True  False   True   True  False  False

In [6]:
three_heads = df.apply(lambda row: row.values.sum() == 3, axis=1).mean()


In [7]:
three_heads

0.22084

In [8]:
more_than_three_heads = df.apply(lambda row: row.values.sum() >= 3, axis=1).mean()


In [9]:
more_than_three_heads

0.85551

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [10]:
n_sim = 100_000
n_driveby = 2

billboards = np.random.choice([1,0], size=(n_sim, n_driveby), p=[.25, .75])

billboards


array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [1, 0],
       [0, 0],
       [0, 0]])

In [11]:
ds_billboards = billboards.sum(axis = 1)

ds_billboards

array([0, 1, 0, ..., 1, 0, 0])

In [12]:
(ds_billboards == 2).mean()

0.06212

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [13]:
nrows = 100_000 # set rows to number of simulations
ncols = 5       # set columns to number of days in each simulation

# create an array of values using random.normal to repesent the number of PopTarts bought in a day
# reshabe that array into trial groups of 5 to represent five days or PopTart buying
rolls = np.random.normal(3, 1.5, nrows * ncols).astype(int).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)
df.head()

0  1  2  3  4
0  7  3  3  3  1
1  5  1  6  5  3
2  2  1  2  3  3
3  4  4  0  1  0
4  3  1  3  0  2

In [14]:
# count the number of bought PopTarts in each row and create a boolean array showing weather the total number of bought PopTarts equals or exceeds 17
# take the mean of the array to get the probability of having poptarts available to by on friday afternoon
odds_of_tarts = df.apply(lambda row: row.values.sum() < 17, axis=1).mean()

odds_of_tarts

0.87775

### 5. Compare Heights

### a. Men have an average height of 178 cm and standard deviation of 8cm.

### b. Women have a mean of 170, sd = 6cm.

### c. Since you have means and standard deviations, you can use np.random.normal to generate observations.

### d. If a man and woman are chosen at random, P(woman taller than man)?

In [15]:
# array of random men's heights
men_height = np.random.normal(178, 8, size = 100_000)
# array of random women's heights
women_height = np.random.normal(170, 6, size = 100_000)
# dataframe of both heights together
heights = pd.DataFrame({'men_height':men_height, 'women_height':women_height})
heights

men_height  women_height
0      171.737905    172.694625
1      182.036446    177.832439
2      178.235589    174.362071
3      186.081555    164.482477
4      173.932295    172.053526
...           ...           ...
99995  191.321439    167.205525
99996  175.320367    171.393037
99997  180.765431    174.959239
99998  177.438079    179.806806
99999  168.124723    169.233462

[100000 rows x 2 columns]

In [16]:
# probability of random woman being taller than random man
(heights.women_height > heights.men_height).mean()

0.21215

### Other method:


In [17]:

n_sim = 100_000

male_height = np.random.normal(178, 8, size = n_sim)

female_height = np.random.normal(170, 6, size = n_sim)

In [18]:

woman_is_taller = (female_height > male_height).mean()
woman_is_taller

0.21422

### 6. a. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

### b. What is the probability that we observe an installation issue within the first 150 students that download anaconda?

### c. How likely is it that 450 students all download anaconda without an issue?

In [19]:
fails = np.random.choice(['fails', 'success'], size = (100_000, 50), p = (1/250, 249/250))


In [20]:

((fails == 'success').sum(axis=1) == 50).mean() # probability of 50 successes

0.81886

In [21]:

fails = np.random.choice(['fails', 'success'], size = (100_000, 100), p = (1/250, 249/250))
((fails == 'success').sum(axis=1) == 100).mean() # probability of 100 successes

0.67199

In [22]:
fails = np.random.choice(['fails', 'success'], size = (100_000, 150), p = (1/250, 249/250))
((fails == 'success').sum(axis=1) == 150).mean() # probability of 150 successes

0.54633

In [23]:
fails = np.random.choice(['fails', 'success'], size = (100_000, 450), p = (1/250, 249/250))
((fails == 'success').sum(axis=1) == 450).mean() # probability of 450 successes

0.16421

### Other method

In [25]:
# corruption chance
corrupted_dl_chance = 1/250
# students in class
n_students = ncols = 50
# class sims
n_class_dl_sim = nrows = 10**6

# array of sims
dl_sim = np.random.random((nrows,ncols))
dl_sim

array([[0.79581789, 0.63920736, 0.76567093, ..., 0.88635157, 0.94313941,
        0.70661834],
       [0.66172972, 0.53539711, 0.3628674 , ..., 0.36413671, 0.88346443,
        0.21192845],
       [0.36320581, 0.06586357, 0.26575863, ..., 0.8607764 , 0.2466266 ,
        0.95878588],
       ...,
       [0.41959457, 0.03843095, 0.7721694 , ..., 0.97790354, 0.68634405,
        0.92561837],
       [0.25414904, 0.08410688, 0.58484466, ..., 0.52594172, 0.66531003,
        0.6649916 ],
       [0.8694482 , 0.87853533, 0.3136519 , ..., 0.443837  , 0.50296898,
        0.19640734]])

In [26]:
# array of booleans where corruption occurs
dl_sim_corrupted = dl_sim < corrupted_dl_chance
# mean where no corruption occurs
(dl_sim_corrupted.sum(axis = 1) == 0).mean()

0.81871

In [27]:
# Test with 100 students
n_students = nolss = 100
dl_sim = np.random.random((nrows,ncols))
dl_sim_corrupted = dl_sim < corrupted_dl_chance
(dl_sim_corrupted.sum(axis = 1) == 0).mean()

0.818824

In [28]:
n_students = 150 # Probability of first 100 students
dl_sim = np.random.random((nrows,ncols))
dl_sim_corrupted = dl_sim < corrupted_dl_chance
(dl_sim_corrupted.sum(axis = 1) >= 1).mean()

0.181637

In [29]:
n_students = 450 # 450 students download without an issue
dl_sim = np.random.random((nrows,ncols))
dl_sim_corrupted = dl_sim < corrupted_dl_chance
(dl_sim_corrupted.sum(axis = 1) == 0).mean()

0.817891

### 7. a. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [30]:
trucks= np.random.choice(['seen', 'no_seen'], size = (100_000,3), p = ([0.7, 0.3]))
((trucks == 'no_seen').sum(axis = 1) == 3).mean()

0.02746

### b. How likely is it that a food truck will show up sometime this week?

In [31]:
trucks= np.random.choice(['seen', 'no_seen'], size = (100_000,3), p = ([0.7, 0.3]))
((trucks == 'seen').sum(axis = 1) >= 1).mean()

0.97314

### Other method

In [34]:
# Chance of food truck arriving
gut_truck_chance = 0.7
# Days tested
days = ncols = 3
# Total simulations
n_truck_sim = nrows = 10**6

truck_sim = np.random.random((nrows,ncols))

In [35]:
# create boolean array
truck_arrives = truck_sim >= gut_truck_chance
pd.DataFrame(truck_arrives)

0      1      2
0       False  False  False
1       False  False  False
2       False  False  False
3       False  False  False
4       False  False  False
...       ...    ...    ...
999995   True  False  False
999996  False  False   True
999997  False  False  False
999998  False  False   True
999999  False   True  False

[1000000 rows x 3 columns]

In [36]:
# find probability of a truck not showing up all 3 days
(truck_arrives.sum(axis=1) == 0).mean()

0.343213

In [ ]:
# How likely is it that a food truck will show up sometime this week?


In [37]:
# change 3 days to 7 days
days = ncols = 7

# copy code
n_truck_sim = nrows = 10**6
truck_sim = np.random.random((nrows,ncols))
truck_arrives = truck_sim >= gut_truck_chance
# probability that a truck will arive at least once in a week
(truck_arrives.sum(axis = 1) >= 1).mean()

0.91756

In [38]:
# remaining days of week test
days = ncols = 4

# copy code
n_truck_sim = nrows = 10**6
truck_sim = np.random.random((nrows,ncols))
truck_arrives = truck_sim >= gut_truck_chance
# probability that a truck will arive at least once in a week
(truck_arrives.sum(axis = 1) >= 1).mean()

0.76018

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [39]:
day_chance = 1/365
people_in_room = ncols = 23
n_birthday_sim = nrows = 10**6

# birthday_sim = np.random.choice(range(0,365+1), size = (nrows,ncols))
birthday_sim = np.random.random((nrows,ncols))
shared_birthday = birthday_sim < day_chance
(shared_birthday.sum(axis = 1) >= 1).mean()

0.061055

In [40]:
people_in_room = ncols = 20
n_birthday_sim = nrows = 10**5

birthday_sim = np.random.random((nrows,ncols))
shared_birthday = birthday_sim < day_chance
(shared_birthday.sum(axis = 1) >= 1).mean()

0.05392

In [41]:
people_in_room = ncols = 40
n_birthday_sim = nrows = 10**5

birthday_sim = np.random.random((nrows,ncols))
shared_birthday = birthday_sim < day_chance
(shared_birthday.sum(axis = 1) >= 1).mean()

0.1021